[package]
name =  "backend"
version = "0.1.0"
edition = "2021"


[dependencies]
actix-web = "4"
actix-multipart = "0.4"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
futures-util = "0.3"
image = "0.25"
bytes = "1"
